### PR TITLE
fix(icons): improve icon page search

### LINKED ISSUE #316: [fomantic-ui.com] Better searching on the fomantic-ui.com website on the icons page
Go to this link: https://fomantic-ui.com/elements/icon.html

With the browsers search feature, try searching for "folder". It shows 0 hits.

Go to the semantic version: https://semantic-ui.com/elements/icon.html

With the browsers search feature, try searching for "folder". It shows 26 hits.

I see the "Search icons ..." text box but I don't want to use that. It would be nice to be able to use the browser search and then see what other icons are related to my search. Thanks.

### PR DESCRIPTION
**Pull request by hammy2899**
Improve the search of the icon page when using native browser
find in page function while keeping performance at best.

This new method hides the individual icons rather then the whole
category however it keeps the icon name visible. Once the icon itself
is within view bounds it will then show it. Using this method the
browser will still search the icon names since the text is still on
show.

Fixes #316

### CODE REVIEW

File: server/files/javascript/icon.js [hunk 1]
```diff
@@ -45,6 +45,23 @@ semantic.icon.ready = function() {
...
+        .each(function () {
+          var element = $(this).get(0);
+          if (iconVisible(element)) {
+            $(this).css('visibility', 'visible');
+          } else {
+            $(this).css('visibility', 'hidden');
+          }
+        });
+    },
     checkVisibility = function() {
```
Comment (lubber-de) [inline server/files/javascript/icon.js:65]: The previous function is now not used anymore. Any reason you kept left it in?

Comment (hammy2899) [reply server/files/javascript/icon.js]: Fixed.

**Review by lubber-de — APPROVED** [review]
LGTM!
